// Package coreactivation connects the core supervisor to finite alias admission
// and the DNS publication gate. It does not own namespace transitions.
package coreactivation

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"sync"
	"syscall"
	"time"

	"mikrocentauri.local/core/internal/config"
	"mikrocentauri.local/core/internal/coreconfig"
	"mikrocentauri.local/core/internal/dnsgate"
	"mikrocentauri.local/core/internal/engineguard"
	"mikrocentauri.local/core/internal/generation"
	"mikrocentauri.local/core/internal/namespace"
	"mikrocentauri.local/core/internal/supervisor"
)

type Namespace interface {
	Snapshot() (namespace.Snapshot, error)
}

// Barrier implementations must prove actual forwarding quarantine and native
// lease revocation. Verify checks ingress and the configured selected path while
// quarantined; Release may open forwarding only after those checks. Methods must
// honor context deadlines. Process existence is insufficient evidence.
type Barrier interface {
	Quarantine(context.Context) error
	Verify(context.Context, coreconfig.Model) error
	Release(context.Context) error
}
type Options struct {
	Directory      string
	Namespace      Namespace
	Ledger         generation.Ledger
	Engine         generation.Engine
	Barrier        Barrier
	Prefix         netip.Prefix
	Capacity       uint32
	Ports          coreconfig.Options
	RealDNSAddress string
	Timeout        time.Duration
}
type Status struct {
	Ready             bool
	Revision          string
	NamespaceRevision uint64
	Admission         generation.Snapshot
}
type Adapter struct {
	lifecycle  sync.Mutex
	mu         sync.Mutex
	registry   sync.Mutex
	opts       Options
	base       namespace.Snapshot
	dir, cache string
	lock       *os.File
	dns        *dnsgate.Switcher
	admission  *generation.Admission
	model      coreconfig.Model
	status     Status
}

func New(o Options) (*Adapter, error) {
	if o.Directory == "" || o.Namespace == nil || o.Ledger == nil || o.Engine == nil || o.Barrier == nil {
		return nil, errors.New("activation dependencies required")
	}
	if o.Timeout == 0 {
		o.Timeout = 10 * time.Second
	}
	if o.Timeout <= 0 || o.Timeout > time.Minute {
		return nil, errors.New("invalid activation timeout")
	}
	if !o.Prefix.IsValid() {
		o.Prefix = netip.MustParsePrefix("198.18.0.0/15")
	}
	if o.Capacity == 0 {
		o.Capacity = 32
	}
	s, err := o.Namespace.Snapshot()
	if err != nil || coreconfig.ValidateNamespaceTransition(s, s) != nil {
		return nil, errors.New("committed namespace required")
	}
	if _, err = generation.New(generation.Config{Selected: s.Known, Active: s.Active, Prefix: o.Prefix, Capacity: o.Capacity}, o.Engine, o.Ledger); err != nil {
		return nil, errors.New("invalid finite admission policy")
	}
	dir, err := filepath.Abs(o.Directory)
	if err != nil || checkPath(dir) != nil {
		return nil, errors.New("unsafe activation registry")
	}
	if err = os.MkdirAll(dir, 0700); err != nil {
		return nil, errors.New("activation registry unavailable")
	}
	st, err := os.Lstat(dir)
	if err != nil || !st.IsDir() || st.Mode().Perm() != 0700 {
		return nil, errors.New("activation registry must be private")
	}
	f, err := os.OpenFile(filepath.Join(dir, "registry.lock"), os.O_CREATE|os.O_RDWR|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0600)
	if err != nil {
		return nil, errors.New("activation registry lock unavailable")
	}
	st, err = f.Stat()
	if err != nil || !st.Mode().IsRegular() || st.Mode().Perm() != 0600 || syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB) != nil {
		f.Close()
		return nil, errors.New("activation registry already owned or unsafe")
	}
	a := &Adapter{opts: o, base: s, dir: dir, cache: filepath.Join(dir, "engine-cache.db"), lock: f, dns: dnsgate.NewSwitcher(nil)}
	a.base.Known = append([]string{}, s.Known...)
	a.base.Active = append([]string{}, s.Active...)
	a.opts.Ports.CachePath = a.cache
	return a, nil
}

// Register persists the validated secret-bearing source model before the caller
// passes its generated bytes to Supervisor.Apply. Reopened LKG revisions can
// consequently resolve the same model without depending on in-memory pointers.
func (a *Adapter) Register(m coreconfig.Model) ([]byte, error) {
	a.registry.Lock()
	defer a.registry.Unlock()
	if a.lock == nil {
		return nil, errors.New("activation registry closed")
	}
	if err := a.current(); err != nil {
		return nil, err
	}
	if m.DNS.FakeIPRange != a.opts.Prefix.String() {
		return nil, errors.New("core pool differs from activation pool")
	}
	b, err := coreconfig.GenerateForNamespace(m, a.base, a.opts.Ports)
	if err != nil {
		return nil, err
	}
	model, err := encodeModel(m)
	if err != nil {
		return nil, err
	}
	path := a.modelPath(digest(b))
	if _, e := os.Lstat(path); os.IsNotExist(e) {
		files, e := os.ReadDir(a.dir)
		if e != nil {
			return nil, errors.New("registry unavailable")
		}
		count := 0
		for _, file := range files {
			if filepath.Ext(file.Name()) == ".json" {
				count++
			}
		}
		if count >= 64 {
			return nil, errors.New("model registry capacity reached")
		}
	}
	if st, e := os.Lstat(path); e == nil && (!st.Mode().IsRegular() || st.Mode().Perm() != 0600) {
		return nil, errors.New("unsafe registered model")
	}
	if checkPath(a.dir) != nil || config.WriteAtomic(path, model) != nil {
		return nil, errors.New("model persistence failed")
	}
	return b, nil
}

func (a *Adapter) Semantic(b []byte) error {
	_, err := a.resolve(b)
	return err
}
func (a *Adapter) resolve(b []byte) (coreconfig.Model, error) {
	a.registry.Lock()
	defer a.registry.Unlock()
	if a.lock == nil || len(b) == 0 || len(b) > 4<<20 || checkPath(a.dir) != nil {
		return coreconfig.Model{}, errors.New("invalid activation candidate")
	}
	if err := a.current(); err != nil {
		return coreconfig.Model{}, err
	}
	data, err := readPrivate(a.modelPath(digest(b)))
	if err != nil {
		return coreconfig.Model{}, errors.New("registered model unavailable")
	}
	m, err := coreconfig.Decode(data)
	if err != nil || m.DNS.FakeIPRange != a.opts.Prefix.String() || coreconfig.ValidateForNamespace(b, m, a.base, a.opts.Ports) != nil {
		return coreconfig.Model{}, errors.New("candidate does not match registered namespace policy")
	}
	return m, nil
}
func (a *Adapter) current() error {
	s, err := a.opts.Namespace.Snapshot()
	if err != nil || !reflect.DeepEqual(s, a.base) {
		return errors.New("namespace changed; activation requires coordinated recovery")
	}
	return nil
}
func (a *Adapter) Hooks() supervisor.Hooks {
	return supervisor.Hooks{Quarantine: a.Quarantine, Prepare: a.prepare, Probe: a.probe, Release: a.release}
}
func (a *Adapter) Quarantine(ctx context.Context) error {
	a.lifecycle.Lock()
	defer a.lifecycle.Unlock()
	return a.quarantineLocked(ctx)
}
func (a *Adapter) quarantineLocked(ctx context.Context) error {
	a.dns.Hold()
	a.mu.Lock()
	a.status.Ready = false
	admission := a.admission
	a.mu.Unlock()
	if admission != nil {
		admission.Revoke()
	}
	bounded, cancel := context.WithTimeout(ctx, a.opts.Timeout)
	defer cancel()
	if a.opts.Barrier.Quarantine(bounded) != nil {
		return errors.New("forwarding quarantine failed")
	}
	return bounded.Err()
}
func (a *Adapter) prepare(ctx context.Context, path string) error {
	a.lifecycle.Lock()
	defer a.lifecycle.Unlock()
	b, err := readPrivate(path)
	if err != nil {
		return errors.New("candidate unavailable")
	}
	m, err := a.resolve(b)
	if err != nil {
		return err
	}
	if err = engineguard.CheckCache(a.cache, len(a.opts.Ledger.Mappings()) > 0); err != nil {
		return errors.New("engine cache preflight denied")
	}
	admission, err := generation.New(generation.Config{Selected: a.base.Known, Active: a.base.Active, Prefix: a.opts.Prefix, Capacity: a.opts.Capacity}, a.opts.Engine, a.opts.Ledger)
	if err != nil {
		return errors.New("admission policy denied")
	}
	active := map[string]bool{}
	for _, n := range a.base.Active {
		active[n] = true
	}
	retired := []string{}
	for _, n := range a.base.Known {
		if !active[n] {
			retired = append(retired, n)
		}
	}
	gate, err := dnsgate.New(dnsgate.Config{InternalAddress: fmt.Sprintf("127.0.0.1:%d", a.opts.Ports.DNSPort), Selected: a.base.Active, Retired: retired, RealAddress: a.opts.RealDNSAddress}, admission)
	if err != nil {
		return errors.New("DNS policy denied")
	}
	if err = a.dns.Install(gate); err != nil {
		return err
	}
	a.mu.Lock()
	a.admission = admission
	a.model = m
	a.status.Revision = digest(b)
	a.status.NamespaceRevision = a.base.Revision
	a.mu.Unlock()
	return ctx.Err()
}
func (a *Adapter) probe(ctx context.Context, path string) error {
	a.lifecycle.Lock()
	defer a.lifecycle.Unlock()
	if _, err := a.resolvePath(path); err != nil {
		return err
	}
	a.mu.Lock()
	admission, m := a.admission, a.model
	a.mu.Unlock()
	if admission == nil {
		return errors.New("admission unavailable")
	}
	// The caller starts sing-box with umask0077. Metadata is checked again after
	// startup; a writable or absent cache never becomes publication readiness.
	for {
		_, statErr := os.Lstat(a.cache)
		if statErr == nil {
			if engineguard.CheckCache(a.cache, true) != nil {
				return errors.New("engine cache metadata denied")
			}
			if a.opts.Barrier.Verify(ctx, m) == nil {
				break
			}
		} else if !os.IsNotExist(statErr) {
			return errors.New("engine cache unavailable")
		}
		select {
		case <-ctx.Done():
			return errors.New("forwarding readiness timeout")
		case <-time.After(20 * time.Millisecond):
		}
	}
	if admission.Admit(ctx) != nil {
		return errors.New("alias/backend admission failed")
	}
	return ctx.Err()
}
func (a *Adapter) release(ctx context.Context) error {
	a.lifecycle.Lock()
	defer a.lifecycle.Unlock()
	if err := a.current(); err != nil {
		return err
	}
	a.mu.Lock()
	admission, m := a.admission, a.model
	a.mu.Unlock()
	if admission == nil || !admission.Snapshot().Admitted {
		return errors.New("unadmitted core generation")
	}
	if engineguard.CheckCache(a.cache, true) != nil || a.opts.Barrier.Verify(ctx, m) != nil {
		return errors.New("release preflight denied")
	}
	// Fresh publication readback for every reserved binding precedes forwarding.
	if admission.Admit(ctx) != nil {
		return errors.New("release backend verification failed")
	}
	if err := a.current(); err != nil {
		return err
	}
	if a.opts.Barrier.Release(ctx) != nil {
		return errors.New("forwarding release failed")
	}
	if err := a.dns.Release(); err != nil {
		return err
	}
	a.mu.Lock()
	a.status.Ready = true
	a.mu.Unlock()
	return ctx.Err()
}
func (a *Adapter) resolvePath(path string) (coreconfig.Model, error) {
	b, err := readPrivate(path)
	if err != nil {
		return coreconfig.Model{}, errors.New("candidate unavailable")
	}
	return a.resolve(b)
}
func (a *Adapter) Handler() dnsgate.Handler { return a.dns }
func (a *Adapter) CachePath() string        { return a.cache }

// Check revalidates admitted aliases and fresh backend readback for cached
// traffic as well as DNS. A failure closes the publication and forwarding gates;
// it is not a guarantee against changes between observation and packet delivery.
func (a *Adapter) Check(ctx context.Context) error {
	a.lifecycle.Lock()
	defer a.lifecycle.Unlock()
	a.mu.Lock()
	ready, admission := a.status.Ready, a.admission
	a.mu.Unlock()
	if !ready || admission == nil {
		return errors.New("core generation not ready")
	}
	bounded, cancel := context.WithTimeout(ctx, a.opts.Timeout)
	defer cancel()
	fail := func() error {
		cleanup, stop := context.WithTimeout(context.WithoutCancel(ctx), a.opts.Timeout)
		defer stop()
		cleanupErr := a.quarantineLocked(cleanup)
		return errors.Join(errors.New("core runtime verification failed"), cleanupErr)
	}
	if a.current() != nil || engineguard.CheckCache(a.cache, true) != nil || admission.Validate(bounded) != nil {
		return fail()
	}
	for _, binding := range admission.Snapshot().Bindings {
		m, ttl, err := a.opts.Ledger.PublishAlias(bounded, binding.Domain, binding.Alias)
		if err != nil || bounded.Err() != nil || m.Domain != binding.Domain || m.Fake != binding.Alias || ttl <= 0 {
			return fail()
		}
	}
	if a.current() != nil || !admission.Snapshot().Admitted {
		return fail()
	}
	return nil
}

// Prune removes only registered models absent from the supervisor's complete
// durable retention set. It never touches the allocator cache or alias ledger.
func (a *Adapter) Prune(retained []string) error {
	a.registry.Lock()
	defer a.registry.Unlock()
	if a.lock == nil || checkPath(a.dir) != nil {
		return errors.New("registry unavailable")
	}
	pattern := regexp.MustCompile(`^[a-f0-9]{64}$`)
	keep := map[string]bool{}
	for _, hash := range retained {
		if !pattern.MatchString(hash) {
			return errors.New("invalid retained revision")
		}
		keep[hash] = true
	}
	files, err := os.ReadDir(a.dir)
	if err != nil {
		return errors.New("registry unavailable")
	}
	for _, file := range files {
		hash := strings.TrimSuffix(file.Name(), ".model.json")
		if !pattern.MatchString(hash) || keep[hash] {
			continue
		}
		path := a.modelPath(hash)
		st, e := os.Lstat(path)
		if e != nil || !st.Mode().IsRegular() || st.Mode().Perm() != 0600 {
			return errors.New("unsafe registered model")
		}
		if os.Remove(path) != nil {
			return errors.New("registry pruning failed")
		}
	}
	f, err := os.Open(a.dir)
	if err != nil {
		return errors.New("registry unavailable")
	}
	defer f.Close()
	if f.Sync() != nil {
		return errors.New("registry pruning persistence failed")
	}
	return nil
}
func (a *Adapter) Status() Status {
	a.mu.Lock()
	defer a.mu.Unlock()
	s := a.status
	if a.admission != nil {
		s.Admission = a.admission.Snapshot()
	}
	return s
}

// Close must follow Supervisor.Close so its mandatory hooks retain registry access.
func (a *Adapter) Close(ctx context.Context) error {
	err := a.Quarantine(ctx)
	a.registry.Lock()
	defer a.registry.Unlock()
	if a.lock != nil {
		syscall.Flock(int(a.lock.Fd()), syscall.LOCK_UN)
		a.lock.Close()
		a.lock = nil
	}
	return err
}
func digest(b []byte) string                    { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func (a *Adapter) modelPath(hash string) string { return filepath.Join(a.dir, hash+".model.json") }
