//go:build linux || darwin

package routeros

import (
	"context"
	"errors"
	"time"
)

// NewManagedController admits active owned objects over TLS. Executable native
// hooks must be generated by this package; the staged constructor remains the
// default for provisioning. This layer does not assert engine/DNS readiness.
func NewManagedController(client *Client, directory string) (*Controller, error) {
	if client == nil || client.base.Scheme != "https" {
		return nil, errors.New("managed controller requires HTTPS")
	}
	c, err := NewLabController(client, directory)
	if err != nil {
		return nil, err
	}
	c.managedOnly = true
	return c, nil
}

func managedValidateObject(instance string, o Object) error {
	if !Owned(instance, o) {
		return errors.New("unsafe managed ownership")
	}
	if o.Fields["disabled"] != "true" && o.Fields["disabled"] != "false" {
		return errors.New("managed state requires explicit disabled boolean")
	}
	switch o.Path {
	case "tool/netwatch":
		if o.Fields["test-script"] != "" || o.Fields["up-script"] != "" || o.Fields["down-script"] != "" {
			return ValidateGeneratedWatchdog(instance, o)
		}
	case "system/scheduler":
		return ValidateGeneratedBootGuard(instance, o)
	}
	return nil
}
func managedValidateChange(instance string, ch Change) error {
	for _, o := range []*Object{ch.Before, ch.After} {
		if o != nil {
			if err := managedValidateObject(instance, *o); err != nil {
				return err
			}
		}
	}
	return nil
}

// Verify compares the complete desired managed set, including absence of extras.
// Runtime-only fields and RouterOS defaults are not caller-owned configuration.
func (c *LabController) Verify(ctx context.Context, instance string, desired []Object) error {
	unlock, err := c.lock()
	if err != nil {
		return err
	}
	defer unlock()
	j, err := c.read()
	if err != nil {
		return err
	}
	if j != nil && (j.Instance != instance || j.State == "pending") {
		return errors.New("verify requires recovered matching instance")
	}
	if _, err = Plan(instance, nil, desired); err != nil {
		return err
	}
	for _, o := range desired {
		if err = c.validateChange(instance, Change{Action: "create", After: &o}); err != nil {
			return err
		}
	}
	rows, err := c.client.Discover(ctx)
	if err != nil {
		return err
	}
	p, err := Plan(instance, rows, desired)
	if err != nil {
		return err
	}
	if len(p.Changes) != 0 {
		return errors.New("managed desired state verification failed")
	}
	return nil
}

// Rollback explicitly compensates the most recent committed transaction too.
// External edits are refused exactly as with interrupted-write recovery.
func (c *LabController) Rollback(ctx context.Context) error {
	unlock, err := c.lock()
	if err != nil {
		return err
	}
	defer unlock()
	j, err := c.read()
	if err != nil || j == nil {
		return err
	}
	if j.State == "rolled-back" {
		return nil
	}
	if j.State == "committed" {
		j.State = "pending"
		if err = c.persist(*j); err != nil {
			return err
		}
	}
	return c.recoverLocked(ctx)
}

// CleanupManaged removes only this instance's exactly owned objects. The same
// transaction validation and placement-aware restoration apply to cleanup.
func (c *LabController) CleanupManaged(ctx context.Context, instance string) error {
	return c.Reconcile(ctx, instance, []Object{})
}

// ApplyTransactional attempts bounded compensation on failure while retaining
// unresolved journals. Managed Apply delegates here; lab/staged Apply retains
// explicit recovery for deliberate crash testing.
func (c *LabController) ApplyTransactional(ctx context.Context, p ChangePlan) error {
	unlock, err := c.lock()
	if err != nil {
		return err
	}
	defer unlock()
	old, err := c.read()
	if err != nil {
		return err
	}
	if old != nil && old.State == "pending" {
		return errors.New("pending transaction requires recovery")
	}
	if err = c.applyLocked(ctx, p); err != nil {
		// Never compensate a foreign or previously pending transaction here: only
		// the journal for this exact newly attempted plan may be rolled back.
		j, readErr := c.read()
		if readErr != nil {
			return errors.Join(err, readErr)
		}
		if j != nil && j.State == "pending" && j.Instance == p.Instance {
			cleanup, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
			defer cancel()
			if recoveryErr := c.recoverLocked(cleanup); recoveryErr != nil {
				return errors.Join(err, recoveryErr)
			}
		}
		return err
	}
	return nil
}

// ValidateManagedDesired validates a complete structured desired set before a preview.
func ValidateManagedDesired(instance string, desired []Object) error {
	if _, err := Plan(instance, nil, desired); err != nil {
		return err
	}
	for _, o := range desired {
		if err := controllerValidateChange(instance, Change{Action: "create", After: &o}); err != nil {
			return err
		}
		if err := managedValidateObject(instance, o); err != nil {
			return err
		}
	}
	return nil
}

// Discover returns a bounded native snapshot under the same controller lock.
func (c *LabController) Discover(ctx context.Context) ([]Object, error) {
	unlock, err := c.lock()
	if err != nil {
		return nil, err
	}
	defer unlock()
	return c.client.Discover(ctx)
}

// Plan previews a fresh desired-state difference without mutating RouterOS.
func (c *LabController) Plan(ctx context.Context, instance string, desired []Object) (ChangePlan, error) {
	unlock, err := c.lock()
	if err != nil {
		return ChangePlan{}, err
	}
	defer unlock()
	for _, o := range desired {
		if err = c.validateChange(instance, Change{Action: "create", After: &o}); err != nil {
			return ChangePlan{}, err
		}
	}
	rows, err := c.client.Discover(ctx)
	if err != nil {
		return ChangePlan{}, err
	}
	return Plan(instance, rows, desired)
}
